# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a416c0190b71297c8166d71aacba33a6ea1e0f7b3937207d2f8425fa3b5c3e5c9b49df6a369e4cb2c3df77781e2f72d24e4254c445ce48795e131d65970d19f2

test:
  secret_key_base: 0e4e8f05c272e55450f4e9e6829f87484b55c00103f32eec5ae8f12d630f3eeffeaf189775d5b516ca771353ccd096afa7727bc271fb3b5fd3995694365b6026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
